### ISSUE TITLE
About sync, can't get it working

### ISSUE THREAD

**Issue by Kostenzer** [mozilla-extensions/aboutsync#137]
About sync, can't get it working.

I hope I'm at the right place for this here.

I installed AbouSync because it could be interesting. It is greyed out, as well en other add-ons
What is the cause it is greyed out?
I want to put this add-on in the toolbar. Unfortunately, it also won't work. 
![about sync](https://github.com/mozilla-extensions/aboutsync/assets/45454004/557f6e6e-0fb8-4622-a66a-a53de105125d)

Do I do something wrong?

Win 11 23H2
Firefox 121.0.1 (64)
AMD Ryzen 7 7735U with Radeon Graphics

**Comment by Kostenzer** [comment]
No, nothing changes, just a page opens with my Firefox Account data

**Comment by mhammond** [comment]
A page opening with your Firefox Account data sounds like it is working?

**Comment by Kostenzer** [comment]
It's not clear to me what you mean.
![about sync](https://github.com/mozilla-extensions/aboutsync/assets/45454004/26ad0c0f-9d91-45d2-8b1a-be2d6f50afd2)

**Comment by mhammond** [comment]
That's working as expected.
