### ISSUE TITLE
Can't view tabs send to another device

### ISSUE THREAD

**Issue by ohhai** [mozilla-extensions/aboutsync#97]
I think I checked all the info shown by the subject addon and still can't see "sent tabs" there.
I mean not the general list of tabs synchronized between devices but only tabs which are sent by "Send Tab to Device" and still are not retrieved by the destination device.

Why I need that: Firefox duplicated some of my devices for some reason and I noticed it too late - after sending some tabs to already inactive device entries. Now I want to get that URLs back but have no way for that. That sent tabs should be still stored on the sync server, so it should be possible to read them from there.

About Sync version 0.21.0buildid20220714.054802, updated 16 Jul 2022
Firefox 104.0, Linux

**Comment by mhammond** [comment]
Sorry, it's impossible for about:sync to get that information :(
